name: Single Waku simulation
description: Request a single Waku simulation and analysis from DST
title: "[Waku] Replace me with a descriptive title"
labels: ["analysis-required", "test-pending"]
assignees:
  - Zorlin
body:
  - type: markdown
    attributes:
      value: |
        Please fill out this form to create a request for a Waku simulation.
        If possible, VacLab will perform the simulation automatically and collect results to be analysed by DST staff later.
        You may specify specific things you wish to be analysed later.
  - type: input
    id: what
    attributes:
      label: What's being tested?
      description: In brief, what is being tested that requires this simulation?
      placeholder: "ex: Waku relay bandwidth usage"
    validations:
      required: true
  - type: textarea
    id: description
    attributes: 
      label: Longer test description
      description: You can go into more detail here about what needs to be done and any specifics about the test.
      placeholder: "We are testing the bandwidth usage of Waku when relaying messages."
  - type: dropdown
    id: milestone
    attributes:
      label: What milestone is this testing being done against?
      multiple: true
      options:
        - vac:dst:deployment-and-analysis:waku:10k
        - vac:dst:deployment-and-analysis:waku:midscale
    validations:
      required: true
  - type: input
    id: image
    attributes:
      label: Docker image
      description: Whaat docker image is required to test the software?
      default: "soutullostatus/example-nwaku:v0.28.0"
    validations:
      required: true
  - type: input
    id: num-nodes
    attributes:
      label: Number of nodes
      description: How many nodes do you want to spawn?
      default: "50"
    validations:
      required: true
  - type: input
    id: num-bootstrap
    attributes:
      label: Bootstrap nodes
      description: How many bootstrap nodes do you want to spawn?
      default: "3"
    validations:
      required: true
  - type: input
    id: duration
    attributes:
      label: Duration
      description: How long do you want to run each deployment for? (in minutes)
      placeholder: "20"
    validations:
      required: true
  - type: dropdown
    id: publisher-enabled
    attributes:
      label: Enable Publisher
      description: Do you want to enable the publisher for this simulation?
      options:
        - "Yes"
        - "No"
    validations:
      required: true
  - type: markdown
    attributes:
      value: |
        ---
        ## Advanced Settings
        
        The following settings are optional. If you don't think you need to change them, you probably don't.
        Only modify these if you have specific requirements for your simulation.
  - type: input
    id: pubsub-topic
    attributes:
      label: PubSub Topic
      description: Specify the PubSub topic to use for the simulation
      default: "/waku/2/rs/2/0"
  - type: input
    id: publisher-message-size
    attributes:
      label: Publisher Message Size
      description: Specify the size of messages published (in KB)
      default: "1"
  - type: input
    id: publisher-delay-seconds
    attributes:
      label: Publisher Delay
      description: Specify the delay between messages (in seconds)
      default: "10"
  - type: input
    id: publisher-message-count
    attributes:
      label: Publisher Message Count
      description: Specify the total number of messages to publish
      default: "1000"
  - type: dropdown
    id: artificial-latency
    attributes:
      label: Enable Artificial Latency
      description: Do you want to simulate network latency?
      options:
        - "Yes"
        - "No"
  - type: input
    id: latency-ms
    attributes:
      label: Artificial Latency (ms)
      description: If enabled, specify the artificial latency in milliseconds
      default: "50"
  - type: dropdown
    id: custom-command
    attributes:
      label: Use Custom Command
      description: Do you want to use a custom command for the Waku nodes?
      options:
        - "Yes"
        - "No"
  - type: textarea
    id: custom-command-args
    attributes:
      label: Custom Command Arguments
      description: If you need to use custom command arguments, specify them here (one per line).
      default: |
        --custom-flags=foo
        --more-custom-flags=bar
