podEnv:
  # a default port must be set. required by container
  - name: "UPTIME_KUMA_PORT"
    value: "3001"
  - name: "NODE_OPTIONS"
    value: "--insecure-http-parser"
ingress:
  enabled: true
  className: "traefik"
  annotations:
    cert-manager.io/cluster-issuer: "acme-prod"   
  hosts:
    - host: status.vaclab.org
      paths:
        - path: /
          pathType: Prefix
  tls:
  - secretName: vaclab-uptime-tls-secret
    hosts:
    - "status.vaclab.org"
